include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generic/src/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    prefer_const_literals_to_create_immutables: ignore
    sort_unnamed_constructors_first: ignore
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules:
    prefer_single_quotes: true
    flutter_style_todos: true
