// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1OExV0OixPN3Z3YRz_G2fgeavP6gjMs',
    appId: '1:731781815007:android:c473818012ba0584a0676a',
    messagingSenderId: '731781815007',
    projectId: 'package-6031d',
    databaseURL: 'https://package-6031d.firebaseio.com',
    storageBucket: 'package-6031d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXRmseIXBVACtTCPSsHAqUlBeSY9cN9w',
    appId: '1:731781815007:ios:920a113015656c2ea0676a',
    messagingSenderId: '731781815007',
    projectId: 'package-6031d',
    databaseURL: 'https://package-6031d.firebaseio.com',
    storageBucket: 'package-6031d.appspot.com',
    androidClientId:
        '731781815007-6phju19k7ss0qe669vs2qfq17c8eihb7.apps.googleusercontent.com',
    iosClientId:
        '731781815007-m9jepjvj8kcne9akssjah0jq2qtc9qkn.apps.googleusercontent.com',
    iosBundleId: 'com.triangle-interactive.package',
  );
}
